behaviors:
  My Behavior: 
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 204800
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 10
        memory_size: 256
      normalize_inputs: true
      normalize_layers: true
    reward_signals:
      extrinsic:
        gamma: 0.998
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 200000000  # Geändert auf 200 Millionen wie gewünscht
    time_horizon: 160
    summary_freq: 30000
environment_parameters:
  # --- Bestehende Parameter (angepasst für Step-basiertes Curriculum) ---
  z_scale_factor_max: # Steuert Streuung des *finalen* Schusses aufs Tor (falls noch gewünscht, sonst anpassen/entfernen)
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: My Behavior # Anpassen, falls nötig
          threshold: 0.5 # 100 Mio / 200 Mio
        value: 0.2 # Enger finaler Schuss
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: My Behavior
          threshold: 1.0 # 200 Mio / 200 Mio
        value: 0.6 # Breiterer finaler Schuss
      - name: Lesson2
        value: 1.0 # Volle Breite finaler Schuss
  direct_shot_target_index: # Steuert Ziel für Direktschüsse
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: My Behavior
          threshold: 0.5
        value: 0 # Ziel Mitte
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: My Behavior
          threshold: 1.0
        value: 0 # Ziel Mitte
      - name: Lesson2
        value: 1 # Ziel z.B. Außen
  # --- NEUER PARAMETER für die Glockenkurve der Trigger-Z-Position ---
  trigger_z_stddev: # Standardabweichung der Normalverteilung für Trigger-Z
    curriculum:
      - name: Lesson0_NarrowTrigger # Kleine Standardabweichung -> Trigger meist nahe 0
        completion_criteria:
          measure: progress
          behavior: My Behavior
          threshold: 0.5 # 100 Mio / 200 Mio
        # Kleiner Wert -> schmale Glocke, Trigger meist um Z=0 (-0.2 bis 0.2 ca. 95% der Zeit)
        value: 0.1 # Kleinere stddev -> noch stärker auf Mitte fokussiert
      - name: Lesson1_MediumTrigger # Mittlere Standardabweichung
        completion_criteria:
          measure: progress
          behavior: My Behavior
          threshold: 0.8 # 160 Mio / 200 Mio
        # Größerer Wert -> breitere Glocke, Trigger streuen mehr
        value: 0.4 # stddev 0.4 -> ca. 95% der Trigger zwischen -0.8 und 0.8
      - name: Lesson2_WideTrigger # Große Standardabweichung
        # Größter Wert -> flachste Glocke, Trigger fast überall (wird auf -1 bis 1 begrenzt)
        value: 0.7 # std